# 构建阶段
FROM node:18-alpine AS build-stage
WORKDIR /app
COPY package*.json ./
COPY pnpm-lock.yaml ./

# 安装pnpm
RUN npm install -g pnpm

# 使用pnpm安装依赖
RUN pnpm install
COPY . .
RUN pnpm run build

# 生产阶段
FROM nginx:stable-alpine AS production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 