import { createApp } from 'vue'
// import App from './01_Setup函数初体验/App.vue'
// import App from './02_Setup定义数据/App.vue'
// import App from './03_Setup其他函数/App.vue'
// import App from './04_Setup中的toRefs/App.vue'
// import App from './06_Setup中ref引入元素/App.vue'
// import App from './08_依赖注入Provide-Inject/App.vue'
// import App from './09_Setup侦听数据变化/App.vue'
// import App from './10_Setup-Hooks练习/App.vue'
// import App from './10_Setup-Hooks练习/App2.vue'
import App from './10_Setup-Hooks练习/App3.vue'
// import App from './11_Setup语法糖/App.vue'
// import App from './12_时钟/App.vue'

createApp(App).mount('#app')
